### ISSUE TITLE
ティザーサイト作成

### ISSUE THREAD

**Issue by saito** [toraya-group/maisonkei.jp#1]
- Dropbox - maisonkei/mkweb_200819/ 以下にイラレ素材あり
- 求人サイトリンク先 https://secure.careermap.jp/recruit/page_toraya_group

**Comment by saito** [comment]
@fuji 
以下原稿修正です。

オープン日が10月末から年明けに変更することになりました。
伴いまして、出会いの文章の最後を修正したくおもいます。

× 今秋オープンの運びとなりました
↓
〇 2021年初春のオープンを目指しています

**Comment by fuji** [comment]
@saito レイアウト実装いたしました。
- https://maisonkei.netlify.app/
  - テキスト内の全角数字を半角へ変更いたしました。
  - 原稿修正 `今秋オープンの運びとなりました` → `2021年初春のオープンを目指しています` 変更いたしました。
  - プロフィール `Restaurant KEI Web Site` のリンク指示がありませんでしたので、自分の方で検索して入れております、こちらで問題無いでしょうか？
  - meta keyword, description の指示いただけますでしょうか。

**Comment by saito** [comment]
@fuji 
サンキュー！

> * テキスト内の全角数字を半角へ変更いたしました。

ありがとう。

> * 原稿修正 `今秋オープンの運びとなりました` → `2021年初春のオープンを目指しています` 変更いたしました。

確認しました。

> * プロフィール `Restaurant KEI Web Site` のリンク指示がありませんでしたので、自分の方で検索して入れております、こちらで問題無いでしょうか？

ありがとう、正しいです。

> * meta keyword, description の指示いただけますでしょうか。

keyword: Maison KEI, メゾンケイ, とらや, 虎屋, 小林 圭, Kei Kobayashi
description: 冒頭の「Maison KEIは、パリの ...」を入れておいてください〜。

**Comment by saito** [comment]
ひとまず cc しつつチェック回しておきました！

**Comment by fuji** [comment]
@saito `keyword`, `description` を更新しました。
- view-source:https://www.maisonkei.jp/

了解しました、ありがとうございます。
> ひとまず cc しつつチェック回しておきました！

**Comment by saito** [comment]
@fuji 
メールの通り、IE11 でのレイアウト崩れの指摘が来てます。今更感あるけど、可能ならサポートしてもらっていいかな？

**Comment by fuji** [comment]
@saito 承知しました。

**Comment by fuji** [comment]
@saito IE11 サポートいたしました。
- https://www.maisonkei.jp/

![スクリーンショット 2020-08-28 10 55 01](https://user-images.githubusercontent.com/79723/91512430-f5c66f00-e91c-11ea-8d6b-fae4c337a8e2.png)

**Comment by saito** [comment]
サンキュー。報告しておきました。待ち。

**Comment by fuji** [comment]
下記対応します。
```
斎藤さま

お世話になっております。
サイトの実装ありがとうございます。確認しました。
弊社の環境では崩れ等なく表示されており問題ありません。

下記２点だけ微調整をお願いします。

①スマホ表示時のロゴのサイズが少し小さく感じたので、
高さを20pxほど大きく変更いただけますでしょうか。

②スマホ表示時のプロフィール写真の横幅を料理の写真と揃えていただけますでしょうか。


このタイミングでのデザイン調整申し訳ありませんが、
どうぞよろしくお願いいたします。
```
cc/ @saito

**Comment by fuji** [comment]
@saito https://github.com/toraya-group/maisonkei.jp/issues/1#issuecomment-682321038 のフィードバックを反映しました。
- https://www.maisonkei.jp/
  - スマホ表示時のロゴのサイズ修正
  - スマホ表示時のプロフィール写真の横幅を料理の写真と揃える

**Comment by fuji** [comment]
ロゴ差し替えのフィードバックに対応します。
```
斎藤さま

お世話になっております。
制作いただいてるティザーサイトにつきまして、
一点修正をお願いできますでしょうか。

現在サイトの上部に入れているロゴマークがFix前のロゴになっていたため、
サイズはそのままで最終のロゴに差し替えをお願いします。
添付が最終版のロゴaiデータになります。

お手数お掛けして申し訳ございませんが、
どうぞよろしくお願いいたします。
```
cc @saito

**Comment by fuji** [comment]
@saito ロゴ画像の差し替えが完了しました。
- https://www.maisonkei.jp/

**Comment by saito** [comment]
サンキュー！

**Comment by saito** [comment]
@fuji 
最終のフィードバック来ました。本日対応お願いします！

- 「Maison KEI 求人サイトへ」のボタンのカラーを「#000000」に変更
- 原稿を差し替え - [MaisonKEI＿HPテキスト0910_4.docx](https://github.com/toraya-group/maisonkei.jp/files/5215951/MaisonKEI.HP.0910_4.docx)

**Comment by fuji** [comment]
@saito 最終フィードバック対応いたしました。
- https://www.maisonkei.jp/

一点確認お願いいします。
`プロフィール` のテキストで星の箇所が数字と漢字が混じっていましたので、漢字で統一しております。

####原稿
'ミシュランガイドにて１つ星、2017年に外国人オーナーシェフとして初めて２つ星を獲得。2020年1月には日本人シェフとして初の三ツ星を獲得。' 

####修正テキスト
`ミシュランガイドにて一つ星、2017年に外国人オーナーシェフとして初めて二つ星を獲得。2020年1月には日本人シェフとして初の三つ星を獲得。`

**Comment by saito** [comment]
原稿もありがとう！　チェック回しておきました。

**Comment by fuji** [comment]
テキストリンクのフィードバックに対応いたします。
```
斎藤さま

お世話になっております。
ボタンカラーの修正ありがとうございます！

一点お伝え漏れをしていたのですが、
プロフィール下のテキストリンクと下線もボタンに合わせて黒に変更お願いします。

お手数お掛けしますが、
どうぞよろしくお願いいたします。
```
cc/ @saito

**Comment by fuji** [comment]
@saito 下記対応いたしました。
> プロフィール下のテキストリンクと下線もボタンに合わせて黒に変更お願いします。

- https://www.maisonkei.jp/
