### ISSUE TITLE
求人バナー表示

### ISSUE THREAD

**Issue by obayashi32** [toraya-group/maisonkei.jp#11]
河野さまメールより
---
山野さま
斎藤さま

お世話になっております。
現在のティザー2、公式サイト共に求人バナーを設置したいとのこと。
ティザー1で最後に表示していたリンク先を設定してください。

求人バナーの位置は
ティザー2では、2つある予約バナーの下の方の付近
公式サイトでは、どこのページ違和感のなくたどり着けるところ
（トップページがどのようになるのかわかりませんが、トップページの下方とか？）

適度に目立つようにお願いします。
また、この求人バナーは、今後常時表記予定とのことです。
（常に社員、アルバイト問わず募集するそうです）

まずは、早めに現在のティザー2にバナー復活をお願いしたいとおもいます。
その際、これまでと同様（予約とも同様）の黒がいいのか、ほかの色形状がいいのかはお任せします。

よろしくお願いいたします。

**Comment by obayashi32** [comment]
📝 
- 蔭山さまへレイアウト作成依頼済み
- レイアウト届き次第、ティザー2 へ優先して実装 @fuji さん

**Comment by obayashi32** [comment]
@fuji 

ティザー2に表示する求人バナーのレイアウトが届きました。
詳細ご確認いただき、実装をお願いいたします。

### 修正箇所
- 求人バナー追加
- 予約ボタンのテキスト修正
  - 現：　＊キャンセルの場合は、当日100％、前日50％のお料理代金×人数分をご請求いたします
　　　　　あらかじめご了承ください
  - 正：　＊当日キャンセルの場合は、お料理代金×人数分を請求させていただきます
<img width="668" alt="スクリーンショット 2021-01-26 14 27 18" src="https://user-images.githubusercontent.com/31329284/105804285-c064a100-5fe2-11eb-95a8-56659836b769.png">

### Dropbox
- `/maisonkei/mkweb_210126/ティザー2` 以下

**Comment by fuji** [comment]
@obayashi32 求人バナー追加・予約ボタンのテキスト修正に対応いたしました。
ご確認お願いいたします。
- https://deploy-preview-20--maisonkei.netlify.app/
- https://github.com/toraya-group/maisonkei.jp/pull/20 プルリクエスト

**Comment by obayashi32** [comment]
@fuji 

ありがとうございます！
先方へチェックに回します。

**Comment by obayashi32** [comment]
本番へ反映し、先方への報告まで完了済みです。
