### ISSUE TITLE
本番サイト実装

### ISSUE THREAD

**Issue by obayashi32** [toraya-group/maisonkei.jp#13]
- 本番サイトの実装対応
- 2021/01/30 本公開予定

**Comment by saito** [comment]
@obayashi32 
ひとまず公開時はお知らせも手動で作成するので、公開時のニュース原稿を河野さんに準備依頼してもらっていいかな？

**Comment by obayashi32** [comment]
📝 
- 河野さんにニュース原稿手配依頼済み、待ち

**Comment by obayashi32** [comment]
@fuji 

お待たせしております。
レイアウトが決まりましたので、下記より詳細をご確認いただき
実装進行をお願いいたします。

ギリギリのスケジュールで申し訳ありませんが、
明日中には実装完了いただき先方にチェック回したいです。

## figma `maisonkei/Design`
### PC
- HOME 
  - `HOME_B_イラストメニュー下`
  - `HOME_予約open`
  - `HOME_menu追従`
- プロフィール
  - `プロフィール`
- お知らせ
  - `お知らせ`
  - `お知らせ_詳細`

### SP
- HOME 
  - `HOME_B_イラストメニュー下`
  - `HOME_sp_menu_open`
  - `HOME_sp_予約open`
  - `HOME_sp_manu追従`
- プロフィール
  - `プロフィール`
- お知らせ
  - `お知らせ`
  - `お知らせ_詳細`

## 実装内容詳細
- TOPページはPC/スマホ共にご挨拶文が終わったあたりから、追従メニューが表示されるイメージです。
- TOPのメインビジュアルは最初はスライドショーで外観や料理を見せて、動画が完成したら差し替える想定のため
現状はダミーでスライド画像作成をお願いいたします。
- 求人バナーはティザーで表示しているURL と同じです。
- Instagram URL https://www.instagram.com/maisonkei.gotemba/?igshid=13hul0l2cdkxb

**Comment by fuji** [comment]
@obayashi32 figma のURLを教えてください、よろしくお願いします。

**Comment by obayashi32** [comment]
@fuji 

失礼しました。
先ほど招待メールお送りしましたので、ご確認をお願いいたします。

**Comment by obayashi32** [comment]
@fuji 

現在実装進行いただいている最中かと思いますが、
公開時、お知らせページに表示する下記テキスト流し込みをお願いいたします。

### お知らせページ
- 日付
2021.01.30
- タイトル
臨時休業のお知らせ
- 本文
2月1日（月）は、臨時休業いたします。
【定休日　毎週火曜日・水曜日】

**Comment by fuji** [comment]
@gommmmmm maison kei サイトの nuxt 化・レイアウトの更新を行いました。
ローカルでは問題ありませんが、プレビューが出来きません。
nuxt の設定等、一度見ていただいてもいいでしょうか、よろしくお願い致します。
- https://github.com/toraya-group/maisonkei.jp/pull/22 プルリクエスト
- https://deploy-preview-22--maisonkei.netlify.app/

**Comment by gommmmmm** [comment]
@fuji
ローカルでは `yarn dev` とかで環境を再現していると思いますが、これはローカルでnuxtのアプリケーションサーバが動いている状態です。
Netlify/Amplifyでは静的なHTMLをホストする形がデフォルトなので、minaで以前やっていたように一旦サイト全体を丸々出力したものをデプロイする必要があります。
今回は `yarn build` で `static/dist` 以下にできる成果物を丸々コミットしてください。

（いまちょうどAmplifyへの移行しているところなのでここからはAmplifyについてだけ説明します）

`feature/xxx` のような名前のブランチにpushすると、AmplifyNetlifyと似た感じでそのブランチ専用のサブドメインにビルド・デプロイを実行します。今回の場合以下でデプロイされたものを閲覧することができます。

https://feature-issue-13-production.daygluvw87w3l.amplifyapp.com/
id: maisonkei-admin
pass: 4fDm6rG)gM32!!}-

ビルドの状況はAWSのAmplfyコンソールから確認することができます。
以前発行したsaito.coのAWSアカウントでログインして以下をみてみてください。ブランチがビルド・デプロイされたものが下図の赤枠です。
https://ap-northeast-1.console.aws.amazon.com/amplify/home?region=ap-northeast-1&code=a41b442dcb361d992239#/daygluvw87w3l

![image](https://user-images.githubusercontent.com/78220/106122225-cbaefc80-619b-11eb-9321-80c3c7830156.png)

なお、通常Amplifyにはソースコードだけを渡し、デプロイしたらビルドされるようにする場合が多いですが、これを試したところどこかで依存している `fsevents` というパッケージがLinuxでは動かないらしく、ビルドに失敗するようでした。これってどういうパッケージだかわかるかな？

```
2021-01-28T09:36:12.928Z [INFO]: info fsevents@2.3.1: The platform "linux" is incompatible with this module.
ironment caching completed
```

**Comment by fuji** [comment]
@gommmmmm 諸々ありがとうございます。

**Comment by fuji** [comment]
@obayashi32 遅くなりましたが、レイアウト実装しました。
レビューお願いいたします。
- https://feature-issue-13-production.daygluvw87w3l.amplifyapp.com/
  - レイアウト確認後 `お知らせ` https://github.com/toraya-group/maisonkei.jp/issues/13#issuecomment-768777525 の記事を作成します。

**Comment by saito** [comment]
📝 
BASIC認証:
maisonkei-admin
4fDm6rG)gM32!!}-

**Comment by saito** [comment]
@fuji 

実装進行ありがとう！
全体としてはとてもよいです。気づいたところ＆申し訳ないけどデザインに修正が入った点をまとめます。

### メイン写真のスライドショー

下記のような演出に変更希望です。
https://www.livnexhouse.co.jp/livnexhouse/

- 横スライドではなくディゾルブに
- 常に左から右にスクロール
- スライドショー写真本番差し替え (メインスライド写真_A)
- 画像下の●を削除
- モバイルは 2:3 に変更

### ヘッダの「ご予約はこちら」の幅
おそらくデザイン指示のミスで、desktop の幅は、常にマウスオーバーと同じ幅を確保するのが正解だと思います。
(只今Figma修正中の模様)

### その他
- ページ下に Instagram アイコンリンク
- プロフィール写真差し替え (プロフィール_A)

**Comment by obayashi32** [comment]
@fuji 

実装ご対応ありがとうございます。
下記のテキスト修正をお願いいたします。

- 出会い（オープン日修正）
今秋オープンの運びとなりました。
↓
1月30日（土）にオープンの運びとなりました。

- メニュー（読点を削除）
＊コースに飲み物、消費税、サービス料は含まれておりません。
↓
＊コースに飲み物、消費税、サービス料は含まれておりません

**Comment by obayashi32** [comment]
@saito 

お知らせページのカテゴリについて、見落としておりました…
こちら登録する必要があると思いますが、河野さんへの確認でよろしいでしょうか。

**Comment by saito** [comment]
@obayashi32 
お知らせはまだカテゴリなくても困らないと思おうので、いったんカテゴリ表示、カテゴリアーカイブは隠そう。

**Comment by obayashi32** [comment]
@saito 
>お知らせはまだカテゴリなくても困らないと思おうので、いったんカテゴリ表示、カテゴリアーカイブは隠そう。

承知しました。

@fuji 
https://github.com/toraya-group/maisonkei.jp/issues/13#issuecomment-769198734, https://github.com/toraya-group/maisonkei.jp/issues/13#issuecomment-769452906 の修正内容と合わせて
お知らせページのカテゴリとアーカイブ表示を非表示にしていただけますでしょうか。

よろしくお願いいたします。

**Comment by fuji** [comment]
@obayashi32 下記修正対応いたしました。
ご確認お願いします。
- https://feature-issue-13-production.daygluvw87w3l.amplifyapp.com/
  - ヘッダ修正
  - その他修正
    - ページ下に Instagram アイコンリンク
    - プロフィール写真差し替え (プロフィール_A)
  - 出会い：テキスト修正
  - メニュー：テキスト修正
  - 料理：画像差し替え
  - 交通案内：画像追加
  - スライド変更
- https://feature-issue-13-production.daygluvw87w3l.amplifyapp.com/news/
  - カテゴリとアーカイブを非表示

**Comment by obayashi32** [comment]
@fuji 
ご対応ありがとうございます。
PC, SP ともに確認しました！

@saito 
ご確認をお願いいたします。

**Comment by saito** [comment]
@fuji 
サンキュー！
一点だけ。スライドショーの一枚目は、白からのフェードでお願いします。

@obayashi32 
昨日来てた河野さんから来てた「お知らせ」の指示がまだ反映されてないかなと。 @fuji に共有して流しこみ確認お願いします。

**Comment by obayashi32** [comment]
@saito 

>昨日来てた河野さんから来てた「お知らせ」の指示がまだ反映されてないかなと。 @fuji に共有して流しこみ確認お願いします。

お知らせ原稿はすでにhttps://github.com/toraya-group/maisonkei.jp/issues/13#issuecomment-768777525 にて共有しております。
藤原さんから実装確認されてから流し込みしますとコメントhttps://github.com/toraya-group/maisonkei.jp/issues/13#issuecomment-769038039 いただいていたので
この後流し込みご対応をお願いいたします！ @fuji

**Comment by fuji** [comment]
@obayashi32 下記対応しました。
- https://feature-issue-13-production.daygluvw87w3l.amplifyapp.com/
  - お知らせ：記事作成
  - スライド：白からのフェードイン

**Comment by obayashi32** [comment]
@fuji 
ご対応ありがとうございます！
記事確認できました。

@saito 
ご確認をお願いいたします！

**Comment by saito** [comment]
@fuji @obayashi32 
進行ありがとう！

先ほど関係者全員にチェック回しました。

河野さんと電話で話したところ、夕方の打ち合わせで写真確認は終わっていて、ひとまず明日に向けては写真の差し替えなどはなくて OK とのことでした。

最後文字校正だけしてもらうので、河野さんから何か戻しが来たら対応よろしくです。

**Comment by obayashi32** [comment]
@saito 

ありがとうございます！

蔭山さんからメールで公開後の修正箇所についてご連絡来ていたので
下記にて共有いたします。

蔭山さまメールより
---
先ほど皆さんとzoom会議をし諸々デザイン確認いただきました。
圭さんと会長さまもご同席いただき、いくつかご意見をいただいたので、
一部写真とテキストの修正をお願いしたいです。

—— 決定事項 —— 
■ 全体の構成、デザインはOK
■ スライド写真はAで決定
■ プロフィール写真もA（お二人が向かい合っているもの）
■ OGP画像は料理のアップで


—— 修正点 —— 
■ TOPスライド｜外観写真
外観と一緒に入口の石の看板が入っているカットがあれば、そちらも検討したいとの要望をいただきました。
看板が建物に対して垂直に立っているので、おそらく無いと思いますが後藤さんに確認します。

■ TOPスライド｜キッチン盛り付け
もっと厨房の様子が分かる写真に差し替えます。セレクトが済み次第お伝えします。

■ テキスト変更
TOPの「出会い」とプロフィールの「佐藤さんの紹介」のテキストが増えるので差し替えをお願いします。

修正はいずれも明日の公開には間に合わないと思いますので、
決定したものから公開後に差し替えていっていただければと思います。

**Comment by fuji** [comment]
@obayashi32 https://github.com/toraya-group/maisonkei.jp/issues/13#issuecomment-768944391 のコメントにあるように、`/static/` 以下で `yarn generate` を実行して、`/static/dist/`以下にできる成果物をコミットしてください。
6皿ランチ金額変更の件、`yarn generate` して、コミットしました。

**Comment by obayashi32** [comment]
@fuji 

ありがとうございます！
テストページから確認できました。

**Comment by obayashi32** [comment]
公開作業完了し、先方への報告まで完了しました。

https://www.maisonkei.jp/
https://www.maisonkei.jp/profile/
https://www.maisonkei.jp/news/
https://www.maisonkei.jp/news/202101/30/

@saito 
こちらのissueは一旦クローズして、
今後は蔭山さんから来ている修正ごとにissue作成し、進行の方がよろしいでしょうか。

**Comment by saito** [comment]
> こちらのissueは一旦クローズして、
> 今後は蔭山さんから来ている修正ごとにissue作成し、進行の方がよろしいでしょうか。

そうだね。この後細かい依頼も各所から来ると思うので、一つ一つ Issue 分けよう。

**Comment by obayashi32** [comment]
@saito 

>この後細かい依頼も各所から来ると思うので、一つ一つ Issue 分けよう。

承知しました。

こちらのissueはクローズします。
ありがとうございました。
