### ISSUE TITLE
ogp 修正

### ISSUE THREAD

**Issue by saito** [toraya-group/maisonkei.jp#15]
https://www.maisonkei.jp/assets/img/share.jpg

が、決定前の古いロゴになっているので要修正。
(Maison が小文字になっているのが正しいロゴ)

**Comment by fuji** [comment]
@saito ogp 画像を修正しました。
- https://www.maisonkei.jp/


下記デバッガーで再スクレイピングを実行しました。
- https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.maisonkei.jp%2F
- https://cards-dev.twitter.com/validator

**Comment by saito** [comment]
@fuji サンキュー！　確認できました。
