### ISSUE TITLE
TOP スライド画像をスワイプすると自動切り替えが止まる

### ISSUE THREAD

**Issue by obayashi32** [toraya-group/maisonkei.jp#28]
蔭山さまメールより
---
また一度スライドをスワイプで切り替えると、
それ以降次の写真に自動で切り替わらなくなるのですが、こちらは意図的なものでしょうか。
僕のPC環境のせいで起こっている可能性もありますが念の為ご確認お願いします。

**Comment by obayashi32** [comment]
@saito @fuji 

私のPC では画像をスワイプすることができませんでした。
ただ実機のスマホでは、たしかにスワイプすると自動切り替えが止まってしまうようです。
ご確認のほどよろしくお願いいたします。

**Comment by fuji** [comment]
📝 @fuji 
- スワイプ外してOK
- 2週目のスライド画像の挙動確認

**Comment by fuji** [comment]
@obayashi32 上記と合わせ https://github.com/toraya-group/maisonkei.jp/issues/27#issuecomment-770676565 の件も対応済みです。
ご確認お願いいたします。
- https://feature-issue-28-slider-update.maisonkei.jp/

**Comment by obayashi32** [comment]
@fuji 
ご対応ありがとうございます。
私の手元では、正常に表示されました。

@saito 
念の為ご確認いただけますでしょうか。
よろしくお願いいたします。

**Comment by saito** [comment]
よいです！

**Comment by fuji** [comment]
@obayashi32 本件、問題なければリリースお願いします。
https://github.com/toraya-group/maisonkei.jp/pull/37 `Pull requests` 作成済みですので、マージしてリリースしてください。

**Comment by obayashi32** [comment]
@fuji 

先方から
