### ISSUE TITLE
本番サーバセットアップ

### ISSUE THREAD

**Issue by saito** [toraya-group/maisonkei.jp#3]
とりあえず Netlify で。

**Comment by saito** [comment]
@fuji 

ひとまずセットアップしました。

https://maisonkei.netlify.app/
password: maisonkei

static ディレクトリ以下にドキュメントルートがある前提にしてます。

必要なら NuxtJS とかでも OK です。

ドメイン設定は引き続きということで。

**Comment by fuji** [comment]
@saito ありがとうございます、確認しました。

**Comment by saito** [comment]
ドメイン設定も終わりました。

https://www.maisonkei.jp

**Comment by saito** [comment]
http://maisonkei.jp からのリダイレクトがうまくいかない (Chrome で警告が出る)ので、DNS を Netlify DNS に変更してみた。

https://app.netlify.com/teams/saitoco/dns/maisonkei.jp

![image](https://user-images.githubusercontent.com/29406/91435138-d853bf80-e8a0-11ea-927f-21daa2ec5b51.png)

**Comment by saito** [comment]
特に状態に変化は無かったので、

- カスタムドメイン削除・追加
- HTTPS 証明書更新

したら直った。。
