### ISSUE TITLE
予約可能月の修正

### ISSUE THREAD

**Issue by obayashi32** [toraya-group/maisonkei.jp#36]
河野さまメールより
---
「予約はこちら」内に記載さてれいる下記の文章にある期間の変更をお願いします。

お電話でのみ、3月末までのご予約を承っております
↓
お電話でのみ、4月末までのご予約を承っております

**Comment by saito** [comment]
@fuji 
これ、毎月更新するの面倒なので、JavaScript で自動に表示変更できるかな？
「翌月末まで予約できる」という単純なルールです。

**Comment by obayashi32** [comment]
@saito 

本修正についてご相談です。

もしルールとして、予約可能な期日が翌々月末で決まっているということであれば、
月が変わるごとにテキストを修正するのではなく、
「お電話でのみ、翌々月末までのご予約を承っております」とすれば良いような気がするのですがいかがでしょうか。

**Comment by fuji** [comment]
@obayashi32 `お電話でのみ、4月末までのご予約を承っております` の箇所、翌々月を js で取得するよう調整しました。
ご確認お願いします。
- https://feature-issue-36-reservation-month-update.maisonkei.jp/
- https://github.com/toraya-group/maisonkei.jp/pull/38

**Comment by obayashi32** [comment]
@fuji 

ご対応ありがとうございます。PC, SP ともに確認できました。
本番へ反映をお願いいたします。

**Comment by fuji** [comment]
@obayashi32 リリースしました。
- https://www.maisonkei.jp/

**Comment by obayashi32** [comment]
@fuji 

早速ご対応いただきありがとうございます。
確認できました。

先方にも報告完了しましたのでこちらのissueはクローズします。
