### ISSUE TITLE
メニュー・予約ボタン表示タイミング調整

### ISSUE THREAD

**Issue by obayashi32** [toraya-group/maisonkei.jp#39]
河野さまメールより
---
現在、「ご予約はこちら」が、「出会い」くらいの場所になると目次と共に表示開始されます。
この表示開始をすこし早めることはできますでしょうか。

見始めてから、
このウェブサイトは、ずっとスクロールして見たい箇所を探さねばならぬのか？
と、すこし探してしまうので、
スマホであれば、トップの写真が画面から消えて「Maison KEI」が表示されるタイミングくらいには
目次と「ご予約はこちら」が見つかると、探さずにすむかとおもいました。

なにか意図や技術的な理由などわからずにお願いしています。
ご検討のほど、よろしくお願いいたします。

**Comment by obayashi32** [comment]
@saito 

メニュー・予約ボタン表示タイミング調整について河野さまから上記コメントいただきました。
元々は、蔭山さまからのご指示で現状の実装（出会いの箇所でメニュー表示）にしております。

私ももう少し表示タイミングを早めてもいいかなと思います。
ご検討をお願いいたします。

**Comment by saito** [comment]
いいと思います！　進めてください！

**Comment by obayashi32** [comment]
@saito 

ご確認ありがとうございます。
進行いたします。

**Comment by obayashi32** [comment]
@fuji 

PC, SP ともにトップの写真が画面から消えて「Maison KEI」が表示されるタイミングで
メニュー・予約ボタンが表示されるように修正いただけますでしょうか。

よろしくお願いいたします。

**Comment by fuji** [comment]
@obayashi32 メニューの表示タイミングを調整しました。
- https://feature-isuue-39-menu-update.daygluvw87w3l.amplifyapp.com/
- https://github.com/toraya-group/maisonkei.jp/pull/40

**Comment by obayashi32** [comment]
@fuji 

ご対応いただきありがとうございます。
先方にチェック回しました。

**Comment by obayashi32** [comment]
@saito 

先方より、メニューの表示タイミングは問題ないけど
ずっとレストランロゴが表示されているのが気になるので
mina SP版のようにスクロール中はメニューが隠れて、
止まると表示される仕様にしたいとコメントいただきました。

斎藤さん的にはいかがでしょうか。
ご検討をお願いいたします。

**Comment by obayashi32** [comment]
@saito 
ご確認いただきありがとうございます。

@fuji 
メニュー表示のタイミングは問題ないのですが、
mina SP版のようにヘッダの表示をスクロールアップした際に出るように修正いただけますでしょうか。
ただしSP 版は、現状の通り画面下のメニューは常時表示でお願いいたします。

どうぞよろしくお願いいたします。

**Comment by fuji** [comment]
@obayashi32 下記対応しました。
> mina SP版のようにヘッダの表示をスクロールアップした際に出るように修正いただけますでしょうか。
> ただしSP 版は、現状の通り画面下のメニューは常時表示でお願いいたします。

- https://feature-isuue-39-menu-scroll-update.maisonkei.jp/

**Comment by obayashi32** [comment]
@fuji 

ご対応いただきありがとうございます！
確認できましたので、先方にもチェック回します。

**Comment by obayashi32** [comment]
📝 
- メニュー表示、スクロールアップの際にヘッダ表示の実装はOKいただき済み
- 予約メニュー高さ調整は#42 で進行 @fuji

**Comment by fuji** [comment]
@obayashi32 本件、問題なければマージしてリリースしてください。
- https://github.com/toraya-group/maisonkei.jp/pull/41

**Comment by obayashi32** [comment]
@fuji 

ありがとうございます。
本番へ反映し、先方への報告も完了しました。
こちらのissueは要件を満たしましたのでクローズします。
残りの追加実装の件は、#42 で進行をお願いいたします。

**Comment by obayashi32** [comment]
@fuji 

度々すみません。
PC版のメニュー表示は当初の通り、トップの写真が画面から消えて「Maison KEI」が表示されるタイミングで
メニュー・予約ボタンが表示されるように修正いただけますでしょうか。

その後、スクロールダウンしたらメニューが消えて
スクロールアップするとメニューが表示される実装にしていただきたいです。

SP版は現状の実装内容で問題ありません。
どうぞよろしくお願いいたします。

- https://www.maisonkei.jp/

河野さまメールより
---
PCで確認したところ、スクロールを下に向けて移動していたり、止まったりしても「ご予約はこちら」が表示されません。
（Googlechrome、InternetExplorerで確認しました）
上にスクロールで戻る動きをしてはじめて、右上に表示されるようでした。
これだと、予約方法を探しているお客さまは、下まで行ってから予約の案内を見落としたか？とおもって戻ろうとして初めて表示されることになりませんか？
トップの写真が消えたあたりから、上部に表示することは可能でしょうか。
なにかほかの理由などあって、この表示の仕方でしたら、理由をお教えいただければとおもいます。
取り急ぎ、気づいたので。

**Comment by fuji** [comment]
@obayashi32 PC メニューを調整しました。
- https://feature-issue-39-pc-menu-update.maisonkei.jp/

**Comment by obayashi32** [comment]
@fuji 

ありがとうございます。
先方にチェック回しました。

**Comment by fuji** [comment]
@obayashi32 ミーティング時に、相談のあった `PC メニュー` を固定表示へ変更しました。
- https://feature-issue-39-pc-menu-update.maisonkei.jp/

**Comment by obayashi32** [comment]
@fuji 

早速ご対応いただきありがとうございます。
こちらで先方にチェック回しました。

**Comment by obayashi32** [comment]
先方からOKいただきましたので、本番へ反映し報告まで完了しました。
ありがとうございました。
