### ISSUE TITLE
ティザーサイト 2 作成

### ISSUE THREAD

**Issue by saito** [toraya-group/maisonkei.jp#4]
ティザーサイトに情報を追加して更新します。

https://www.dropbox.com/sh/fso1u23jwcz422x/AADrVjEFGimoAmn0jKU84nxLa?dl=0

にレイアウト・指示書を保存しました。

ウェブフォントの指定があります。

- 英語は Google Fonts を使う
- 日本語は下記の TypeSquare を使う

ということでお願いします。

```html
<script type="text/javascript" src="//typesquare.com/3/tsst/script/ja/typesquare.js?rU8A2bw0hwQ%3D" charset="utf-8"></script>
```
Netlify には Deploy Previews 機能があるので、Pull Request 作ればプレビュー用のデプロイが走って URL が自動で発行されます。

**Comment by saito** [comment]
@fuji 
というわけで一旦実装お願いします！　明日 1/7 中に一度チェック回したいなと。

**Comment by fuji** [comment]
@saito ティザーサイトを更新しました、レビューをお願いします。
- [maisonkei.20210107.zip](https://github.com/toraya-group/maisonkei.jp/files/5780147/maisonkei.20210107.zip)

プロフィール画像のみ後日差し替えがあるようです。
<img width="893" alt="スクリーンショット 2021-01-07 16 32 33" src="https://user-images.githubusercontent.com/79723/103864508-1215bc00-5106-11eb-8d5a-21a342aab207.png">


Netlify のアカウント情報が無いため、`Pull Request` まで作成しました。
- https://github.com/toraya-group/maisonkei.jp/pull/5
> Netlify には Deploy Previews 機能があるので、Pull Request 作ればプレビュー用のデプロイが走って URL が自動で発行されます。

**Comment by saito** [comment]
@fuji 
サンキュー！

> Netlify のアカウント情報が無いため、`Pull Request` まで作成しました。

https://github.com/toraya-group/maisonkei.jp/pull/5

の `Deploy preview ready!` の右の `Details` から自動でリンクされます。

https://deploy-preview-5--maisonkei.netlify.app/

実装はよいのでこれで一旦チェック回します！

- プロフィール写真差し替え
- 料理セクションの構成変更あるかも

って点のみ明日連絡もらえると思います。

**Comment by saito** [comment]
@fuji 
主にテキストなんだけど、細かい戻し・変更が週明け来ます。
忘れないうちに Googleマップのリンク先だけ共有します。

https://goo.gl/maps/biu7fEQD2mzD4PL97

**Comment by saito** [comment]
@obayashi32 
蔭山さんから最終指示来たら確認とフジ君へのパスお願いします！

**Comment by obayashi32** [comment]
@fuji 

お待たせしております。
修正データが届きましたので、下記より詳細ご確認いただきご対応をお願いいたします。
なお、 **今週公開するのは電話番号の記載がないレイアウトです。**
よろしくお願いいたします。

### TAKAIYAMA さまより修正指示、差し替え素材
- Dropbox `/maison kei/mkweb_210112` 以下

### 上記以外の追加修正箇所
`/maison kei/mkweb_210112/mkweb_210112.ai` 指示書以外で修正が必要な箇所は下記です。
- 「出会い」「プロフィール」などの見出しのletter-spacingを、日本語3px、欧文1px空ける
- 「メニュー」のランチ「9,800円（8 ～ 10 皿）」ディナー「10,500円（8 ～ 10 皿）」削除 
<img width="310" alt="スクリーンショット 2021-01-12 15 46 09" src="https://user-images.githubusercontent.com/31329284/104279354-8036f600-54ed-11eb-8d48-7419b83a925e.png">

- 「交通案内」のGoogle MAP リンク先を下記 URL に変更
https://goo.gl/maps/biu7fEQD2mzD4PL97
<img width="899" alt="スクリーンショット 2021-01-12 15 46 00" src="https://user-images.githubusercontent.com/31329284/104279367-862cd700-54ed-11eb-8e96-d968553449a9.png">

**Comment by fuji** [comment]
@obayashi32 https://github.com/toraya-group/maisonkei.jp/issues/4#issuecomment-758453675 のフィードバック反映いたしました。
レビューお願いいたします。
- https://deploy-preview-5--maisonkei.netlify.app/

**Comment by obayashi32** [comment]
@fuji 

早速ご対応いただきありがとうございます！
先方から追加でテキスト箇所の修正依頼がきたので、最新版のレイアウトが届きましたら
改めてコメントいたします。

Cc @saito

**Comment by saito** [comment]
@obayashi32 
河野さんから来てるテキスト修正だけど、レイアウト関係ないような。明日には必ず公開したいけど丸一日止まっちゃってるので、一旦 @fuji に修正依頼出してもらっていいかな？

**Comment by saito** [comment]
@obayashi32 
そうだ。一応確認だけど、プロフィール写真って小泉さんから最新版もらってる or 蔭山さんのレイアウトに最新版に差し替わってる？
アタリ写真のまま一度フジ君に組んでもらってます。

**Comment by obayashi32** [comment]
@saito 

ご確認いただきありがとうございます。
>一旦 @fuji に修正依頼出してもらっていいかな？

承知しました。

> 一応確認だけど、プロフィール写真って小泉さんから最新版もらってる or 蔭山さんのレイアウトに最新版に差し替わってる？

先方に確認したところ、現状の写真から差し替え必要ないとのことでした。

河野さまメールより
---
お世話になっております。
小泉に代わりまして、プロフィール写真についてお返事いたします。

現在、デザインに入れていただいている写真をそのまま使用して問題ないそうです。
（修正版への差し替えなし）

**Comment by obayashi32** [comment]
@fuji 

下記のテキスト修正ご対応をお願いいたします。

### 予約バナー
旧：予約受付開始日　1月18日（月）
新：予約受付開始日　1月18日（月）10:00より

### 出会い（テキスト最後）
旧：～今秋オープンの運びとなりました。
新：～このたびオープンの運びとなりました。

### 料理
旧：＊ 1/26（火）～28（木）のプレオープン期間は特別メニュー5,500円にて営業いたします。
新：＊ 1/26（火）～28（木）のプレオープン期間は特別メニュー（ランチ5,500円、ディナー6,500円）にて営業いたします。

### 定休日
旧：火曜日・水曜日
新：
火曜日・水曜日
※2月1日（月）は臨時休業

↑
米印の表記は、他の記載方法と同様に「*」と文字サイズ小さくして表記をお願いいたします。
<img width="506" alt="スクリーンショット 2021-01-14 8 06 53" src="https://user-images.githubusercontent.com/31329284/104521050-8a690980-563f-11eb-9ee5-20a06db8d61a.png">

**Comment by fuji** [comment]
@obayashi32 テキスト修正の対応が完了しました。
- https://deploy-preview-5--maisonkei.netlify.app/

**Comment by saito** [comment]
@fuji 
サンキュー！

@obayashi32 
見た感じ良さそうなので、テキストが指示通りになっていることが確認できたら、山野さん・蔭山さんと、虎屋さん同時に最終チェック回してもらっていいかな？

で、修正あれば調整して、OK になったら master にマージすれば自動で公開されるので、公開・報告までお願いします！

**Comment by obayashi32** [comment]
@fuji @saito 

ありがとうございます。
先方にチェック回しました。

**Comment by obayashi32** [comment]
@fuji 

先方から修正依頼がきました。
添付PDF も合わせてご確認いただき、ご対応をお願いいたします。

蔭山さまメールより
---
>外観イラスト下の「2021年〜OPEN」が少し大袈裟な感じがしたので、
添付PDF1ページ目の様に調整いただけますでしょうか
2、3ページ目も微調整ですがお願いします。
>
>またiPadで見た際ロゴが大きく見えるのでiPadの画面幅の時だけ、
widthを190pxに変更いただけますでしょうか。

### PDF
[kei修正_210114.pdf](https://github.com/toraya-group/maisonkei.jp/files/5812594/kei._210114.pdf)

**Comment by fuji** [comment]
@obayashi32 下記対応が完了しました。
レビューお願いいたします。
> 先方から修正依頼がきました。
> 添付PDF も合わせてご確認いただき、ご対応をお願いいたします。

- https://deploy-preview-5--maisonkei.netlify.app/

**Comment by obayashi32** [comment]
@fuji 

ご対応ありがとうございます。
こちらで先方にチェック回します。

**Comment by obayashi32** [comment]
@fuji 

度々すみません。
下記のご対応をお願いいたします。

>一点だけ「OPEN」の部分は改行せずに、
上の日付と同じ級数にして一行でおさめていただけますでしょうか。

<img width="1042" alt="スクリーンショット 2021-01-14 17 03 54" src="https://user-images.githubusercontent.com/31329284/104561301-8910fe80-568a-11eb-9fec-85e72158a242.png">

**Comment by fuji** [comment]
@obayashi32 下記対応しました。
> 一点だけ「OPEN」の部分は改行せずに、
> 上の日付と同じ級数にして一行でおさめていただけますでしょうか。

- https://deploy-preview-5--maisonkei.netlify.app/

**Comment by obayashi32** [comment]
@fuji 

ありがとうございます！
こちらで先方チェック回しました。

先方からOK出ましたら、すぐに本番公開したいのですが
私の方でhttps://github.com/toraya-group/maisonkei.jp/pull/5 をマージしてしまって問題ないでしょうか？

**Comment by obayashi32** [comment]
@fuji 

度々すみません
こちらで最後の修正です。
下記、ご対応いただけましたらそのまま本番へ反映をお願いいたします。

蔭山さまより
---
>最後に細かいですが「2021年 1月30日 OPEN」全体に
letter-spacing: 1pxをかけておいてください。
>
>その他は問題ありませんので上記反映して公開お願いします。

Cc @saito

**Comment by fuji** [comment]
@obayashi32 はい、問題ありません。

**Comment by fuji** [comment]
@obayashi32 `2021年 1月30日 OPEN` letter-spacing 追加しました。
 - https://deploy-preview-5--maisonkei.netlify.app/

**Comment by obayashi32** [comment]
@fuji 

早速ありがとうございます！
先ほど私の方でマージしたのですが、フォントがテストページと異なるように見えます…
お手数ですが、ご確認いただけますでしょうか。

https://www.maisonkei.jp/

よろしくお願いいたします。

**Comment by fuji** [comment]
@obayashi32 font-family を調整しました。
- https://www.maisonkei.jp/

**Comment by obayashi32** [comment]
@fuji 
ありがとうございます！
確認できました。

@saito 
本番反映まで完了し、先方への報告まで完了しました。
https://www.maisonkei.jp/

**Comment by obayashi32** [comment]
@fuji 

1/18 (月)予約開始時に再度更新が必要になります。
下記、ご対応をお願いいたします。

### 修正箇所
- 「予約受付開始日　1月18日（月）10:00より」箇所を電話番号記載の開閉式レイアウトに変更
<img width="790" alt="スクリーンショット 2021-01-14 18 25 32" src="https://user-images.githubusercontent.com/31329284/104571006-f1191200-5695-11eb-8df9-050c80eaf9a9.png">
<img width="785" alt="スクリーンショット 2021-01-14 18 25 39" src="https://user-images.githubusercontent.com/31329284/104571009-f24a3f00-5695-11eb-883d-d8d5b365f8af.png">

- 「出会い」のテキスト変更
旧：～このたびオープンの運びとなりました。
新：～1月30日（土）にオープンの運びとなりました。
<img width="1148" alt="スクリーンショット 2021-01-14 18 29 55" src="https://user-images.githubusercontent.com/31329284/104571624-a6e46080-5696-11eb-8d11-28c243040612.png">


### TAKAIYAMA さまより修正指示、差し替え素材
- Dropbox `/maison kei/mkweb_210112` 以下

**Comment by obayashi32** [comment]
@fuji 

すみません、昨日本番反映したサイトに誤字が見つかりました。
下記箇所の修正ご対応をお願いいたします。

- https://www.maisonkei.jp/

###  修正箇所
＜料理＞のテキスト2行目
誤：それは、わたしたしが手を…
正：それは、わたしたちが手を…

<img width="574" alt="スクリーンショット 2021-01-15 8 52 48" src="https://user-images.githubusercontent.com/31329284/104662903-2150c700-570f-11eb-8520-fcc7c4b84021.png">

**Comment by obayashi32** [comment]
@saito 
ありがとうございます。

@fuji 
テキスト修正はこちらで対応しました！
https://github.com/toraya-group/maisonkei.jp/issues/4#issuecomment-760076935 の1/18 更新分を本日早めにテストページに反映いただけますと幸いです。
よろしくお願いいたします。

**Comment by fuji** [comment]
@obayashi32 `1/18 (月)予約開始時` の更新対応しました。
レビューお願いいたします。
- https://deploy-preview-8--maisonkei.netlify.app/
- プルリクエスト https://github.com/toraya-group/maisonkei.jp/pull/8

**Comment by obayashi32** [comment]
@fuji 
ご対応いただきありがとうございます！
確認いたしました。

@saito 
1/18 更新分をテストページに反映いただきました。
こちらで先方にチェック回します。

**Comment by obayashi32** [comment]
@fuji 

先方より修正依頼がきました。
下記よりご確認いただき、ご対応をお願いいたします。

蔭山さまメールより
---
### サイトネーム
タブと検索で表示されるサイトネームが「MAISON KEI」になっておりました。
ロゴに合わせて「Maison KEI」に変更お願いします。

### 見出し 日本語
前回「プロフィール」にしていただいた調整、
「マージン-2px」を他の見出しにも適用お願いします。

<img width="416" alt="スクリーンショット 2021-01-15 16 14 32" src="https://user-images.githubusercontent.com/31329284/104693318-ca69e280-574c-11eb-9762-51ce89887682.png">

### 店舗情報 住所
住所に誤りがあったので下記に修正お願いします。
誤：静岡県御殿場市東山1022-1
↓
正：静岡県御殿場市東山527-1

**Comment by fuji** [comment]
@obayashi32 https://github.com/toraya-group/maisonkei.jp/issues/4#issuecomment-760702262 の対応が完了しました。
- https://www.maisonkei.jp/
- https://deploy-preview-8--maisonkei.netlify.app/

**Comment by obayashi32** [comment]
@fuji 

早速ご対応いただきありがとうございます。
検索したときのサイト名がまだ「MAISON KEI」 のままのようですが
こちらは少し時間がかかりますでしょうか。

<img width="739" alt="スクリーンショット 2021-01-15 16 48 19" src="https://user-images.githubusercontent.com/31329284/104696369-85947a80-5751-11eb-90fb-b42fec1148c5.png">

**Comment by fuji** [comment]
@obayashi32 はい、こちらはすぐには反映されません。
> 検索したときのサイト名がまだ「MAISON KEI」 のままのようですが
> こちらは少し時間がかかりますでしょうか。

Search Console からインデックスを再送してください。
- https://developers.google.com/search/docs/advanced/crawling/ask-google-to-recrawl?hl=ja

**Comment by obayashi32** [comment]
@fuji 

承知しました。
ありがとうございます。

**Comment by obayashi32** [comment]
@fuji 

下記修正ご対応をお願いいたします。

### 修正内容
- 「ご予約はこちら」開いた状態の「3月末日までの予約を承っています」下部にテキスト追加
<img width="670" alt="スクリーンショット 2021-01-16 14 19 47" src="https://user-images.githubusercontent.com/31329284/104798055-c7cbc380-5806-11eb-93c1-f618d6802163.png">

### 追加テキスト
```
* スマートカジュアルを推奨しております。
  男性の半ズボンやサンダルなど、極度にカジュアルな服装はご遠慮ください。

* お子様同伴の場合は、個室のみのご予約とさせていただきます。

* 当日キャンセルの場合は、100％のお料理代金×人数分を請求させていただきます。
```

### レイアウトイメージ
- 背景は白になっていますが、黒背景白文字のままでお願いいたします。
<img width="639" alt="スクリーンショット 2021-01-16 14 22 12" src="https://user-images.githubusercontent.com/31329284/104798035-9eab3300-5806-11eb-9e8b-d1724865b2f8.png">

**Comment by fuji** [comment]
@saito @obayashi32 予約ボタンに注釈追加しました。
レビューお願いします。
- https://deploy-preview-8--maisonkei.netlify.app/

**Comment by obayashi32** [comment]
@fuji 

ご対応いただきありがとうございます！
修正箇所を確認できました。

こちらで念の為先方にも報告し、
1/18(月) 10:00 になりましたら私の方でマージいたします。

Cc @saito

**Comment by obayashi32** [comment]
@saito @fuji 

本日10:00 に修正内容を本番へ反映し、先方への報告も完了しました。
- https://www.maisonkei.jp/

こちらのissueはクローズします。
ありがとうございました。

**Comment by obayashi32** [comment]
河野さまより
---
バナー「ご予約はこちら」をタップすると、黒い矩形が開きます。
そのなかの
「3月末までのご予約を承っています」を
「お電話でのみ、3月末までのご予約を承っております」
と変更をお願いいたします。

本日まだオープンしていない店舗に、予約のために徒歩でお越しになった方がおり
電話のみの文言がなかったとのお話をいただいたとのこと。

@saito @fuji 
上記修正内容を対応し、先方へ報告まで完了しました。
- https://www.maisonkei.jp/

**Comment by obayashi32** [comment]
下記修正対応済み、本番へ反映し先方報告完了しました。

河野さまメールより
---
文末を、
います→おります

※印のテキストには「。」を付けない
に表記を統一してください。

**Comment by obayashi32** [comment]
📝 
 - テキスト追加対応あり、テキスト待ち

**Comment by obayashi32** [comment]
河野さまメールより
---
先日お伝えしていたキャンセルポリシーの文言変更をお願い致します。
現在、予約電話番号の下に掲載されているキャンセルポリシーの文言を下記の文言に変更をお願いいたします。
急で申し訳ないのですが、本日中にお願いできますでしょうか。
（明日より一般のお客様がお越しになるため）


キャンセルの場合は、当日100%、前日50%のお料理代金×人数分をご請求いたします
あらかじめご了承ください

**Comment by obayashi32** [comment]
@saito 

河野さまからの最終テキスト修正対応を本番反映し、
先方への報告まで完了しました。

こちらのissueはクローズします。
