### ISSUE TITLE
SP版予約メニュー高さ調整

### ISSUE THREAD

**Issue by obayashi32** [toraya-group/maisonkei.jp#42]
#39 関連

河野さまメールより
---
一つご相談です。
スマホで画面下に表示される「ご予約はこちら」の黒い帯の幅がすこし細い気がしました。
いかがでしょうか？
最近お店にお越しになる高齢なお客さまだと、タップしにくい細さかと想像しました。
画面の見た目のデザイン性もあるので、わたくしの杞憂であれば、そのままで結構です。

蔭山さまメールより
---
スマホ下の予約のエリアですが現在48pxの高さで、
google・apple等で採用されているの最小ボタンサイズはクリアするように制作しております。
よりご高齢の方が気付きやすくするのであれば、
少しだけサイズを高くすることを検討しても良いかもしれません。

＞大林さま
お手数ですが予約メニューの高さを56pxにしたバージョンのデモをアップしていただけますでしょうか。
その際右下のハンバーガーメニューが正方形になるよう幅も56pxにしてください。

**Comment by obayashi32** [comment]
@fuji 

ご対応いただいた#39 とは別に、スマホ版予約メニューの高さを調整してほしいと依頼がありました。
お手数ですが、下記の通りご調整いただけますでしょうか。
よろしくお願いいたします。

>お手数ですが予約メニューの高さを56pxにしたバージョンのデモをアップしていただけますでしょうか。
その際右下のハンバーガーメニューが正方形になるよう幅も56pxにしてください。

Cc @saito

**Comment by fuji** [comment]
@obayashi32 SP版メニューの高さを `56px` へ変更しました。
レビューお願いします。
- https://feature-issue-42-sp-menu-heightadjustment.daygluvw87w3l.amplifyapp.com/

**Comment by obayashi32** [comment]
@fuji 

ご対応ありがとうございます！
実機からも確認できました。

こちらで先方にもチェック回します。

**Comment by obayashi32** [comment]
@saito 

河野さんよりSP版のメニュー表示について下記の相談が来ております。

蔭山さんにレイアウト再調整お願いしてよろしいでしょうか。
ご確認をお願いいたします。

河野さまメールより
---
SP版について、ご相談です。
こちらの使用している電話のデザインによるものなのですが、
画面の縁が黒いため、「予約はこちら」が同化してしまい、見つけにくいという意見がありました。
黒い部分の厚みというだけでなく、もうすこし見つけやすい色？形状？などご提案いただくことは可能でしょうか。
（求人のボタンはすぐわかるということでした。）

**Comment by obayashi32** [comment]
📝 
- ボタンの高さ再度調整中 (山野さま、蔭山さま)

**Comment by obayashi32** [comment]
@fuji 

SP 版メニュー高さ70 px に再修正いただきました。
figma よりご確認いただき、修正ご対応をお願いいたいます。

- figma Design `TOP_sp_manu_高さ調整`


Cc @saito

**Comment by fuji** [comment]
@obayashi32 SP 版メニューの高さを 70 px に変更しました。
- https://feature-issue-42-sp-menu-heightadjustment.daygluvw87w3l.amplifyapp.com/
- https://github.com/toraya-group/maisonkei.jp/pull/49

**Comment by obayashi32** [comment]
@fuji 

ご対応いただきありがとうございます。
修正内容を実機から確認できましたので、先方へチェックに回しました。

**Comment by saito** [comment]
特に反対意見とか無かったので、僕の判断で公開・報告しておきました！
