### ISSUE TITLE
プロフィールページに肩書き追加

### ISSUE THREAD

**Issue by obayashi32** [toraya-group/maisonkei.jp#43]
- https://www.maisonkei.jp/profile/

河野さまメールより
---
お世話になっております。
プロフィールページの小林圭さんと佐藤充宜さんのお名前の前に、肩書を追記いただきたいです。
小林さま、光晴社長、小泉が検討した結果です。

Chef　小林圭…
Maison KEI Chef　佐藤充宜…

**Comment by obayashi32** [comment]
📝 
- 蔭山さまにレイアウト作成依頼済み

**Comment by obayashi32** [comment]
@fuji 

プロフィールページへの肩書き追加実装進行をお願いいたします。
- figma PC, SP `/Design/プロフィール_A`

**Comment by fuji** [comment]
@obayashi32 肩書き追加しました、自明な内容でしたので公開作業まで完了しております。
- https://www.maisonkei.jp/profile/

**Comment by obayashi32** [comment]
@fuji 

ご対応ありがとうございます。
先方への報告まで完了しましたのでこちらのissueはクローズします。
