### ISSUE TITLE
ニュース記事追加

### ISSUE THREAD

**Issue by obayashi32** [toraya-group/maisonkei.jp#47]
河野さまメールより
---
週末に急なお願いとなってしまい恐縮ですが、
メゾンケイのウェブサイト内「お知らせ」に、ひとつ記事を追加をお願いいたします。

-----------

- タイトル

4月末まで満席のお知らせ

- 本文

現在、4月末までのご予約を承っている期間ではございますが、
ランチ・ディナー共にご予約で満席となりました。
キャンセル待ちのご希望は承りますが、お席確保のお約束ではございません。
ご理解のほど、よろしくお願いいたします。

ご予約は、毎月1日に2か月後の末日までの分を承っております。
5月1日（土）～31日（月）のご予約は、3月1日（木）より受付開始いたします。
ご予約はお電話のみとなっております。

ご予約・お問合せ
0550-81-2232
（ご予約受付時間　営業日の10:00～11:30、15:00～17:30）

-----------

たいへん申し訳ないのですが、できるだけ早めに追加いただければとおもいます。
よろしくお願いいたします。

**Comment by obayashi32** [comment]
@fuji 

ニュース記事追加ご対応お願いできますでしょうか。
よろしくお願いいたします。

**Comment by fuji** [comment]
@obayashi32 `お知らせ` 更新しました。
確認お願いします、プルリクエストも作成済みです。
- https://feature-issue-49-news-update.daygluvw87w3l.amplifyapp.com/
- https://feature-issue-49-news-update.daygluvw87w3l.amplifyapp.com/news/
- https://feature-issue-49-news-update.daygluvw87w3l.amplifyapp.com/news/202102/21/
- https://github.com/toraya-group/maisonkei.jp/pull/48

**Comment by obayashi32** [comment]
@fuji 

休日のところ迅速にご対応いただきありがとうございました。
staging 確認できましたので、本番へ反映し先方にも報告済みです。

こちらのissueは要件を充しましたのでクローズします。

Cc @saito
