### ISSUE TITLE
02.21 お知らせ修正

### ISSUE THREAD

**Issue by saito** [toraya-group/maisonkei.jp#50]
- 電話番号修正
- タイトル修正
- 曜日修正

お知らせに掲載してる電話番号も間違っていました！
すみません、至急直していただけますでしょうか
2232
↓
2231

**Comment by obayashi32** [comment]
@saito @fuji 

ご対応ありがとうございました。
先方への修正報告まで完了しましたので、こちらのissueはクローズします。
