### ISSUE TITLE
求人ページ作成

### ISSUE THREAD

**Issue by obayashi32** [toraya-group/maisonkei.jp#54]
### 要件
- 求人ページ追加作成
  - maisonkei.jp の求人ボタンから、サイト内の求人簡単説明ページに移動
  - 求人ページ内にボタンを作成、クリックすると求人アドレスの記載されたメールが立ち上がる

### 素材
- [x] 原稿
- [x] アドレス

河野さまメールより
---
斎藤さま

お世話になっております。
先日はお電話でもお教えいただき、ありがとうございました。
ご提案いただいたように、今回は、
・現在ウェブページの下部にある求人ボタンから、サイト内の求人簡単説明ページに移動。
・そのページ内にボタンを作成していただき、クリックすると求人アドレスの記載されたメールが立ち上がる。
このような、イメージにしようとおもいます。
（求人用の情報を入力するフォームも検討しましたが、毎月多少の費用がかかるとのお話もあったのでなしとします）

求人の簡単説明の文言と、求人用のアドレスを取得次第またご連絡させていただきます。
よろしくお願いいたします。

**Comment by obayashi32** [comment]
@obayashi32 

ワイヤー作成
- 素材
Dropbox `/maisonkei/210323_Maison KEI求人資料.docx`

**Comment by obayashi32** [comment]
@saito 

ワイヤー作成しました。
お手数ですが、figma  よりご確認をお願いいたします。

### figma Desktop, Mobile
- `RECRUIT A`: 先方からのテキストそのまま反映しました
- `RECRUIT B`: 正社員とアルバイトに小見出しをつけて表記しています

**Comment by saito** [comment]
@obayashi32 
B が分かりやすくてよいです！

一点大きなところなんだけど、今回応募はメールアドレスを表示して mailto のリンクを張ることにします。
以前やりとりあったけど、それを難読化してスパムはなるべく来ないようにはするんだけど。

なので、「採用申し込み」のボタンを用意するのではなくて、「応募方法」みたいな見出しを立てて、メールに含めるべき内容を示すべきなんだけど、そういう原稿は無かったかな？　もし無ければこちらで提案する必要があるのでワイヤーフレームの更新をよろしくお願いします。

**Comment by obayashi32** [comment]
@saito 

ご確認いただきありがとうございます。
河野さんのメールにボタン作成とあったので勘違いしておりました。失礼しました。

>「応募方法」みたいな見出しを立てて、メールに含めるべき内容を示すべきなんだけど、そういう原稿は無かったかな？　
> もし無ければこちらで提案する必要があるのでワイヤーフレームの更新をよろしくお願いします。

ご共有いただいた原稿にはアドレスしか表記されていませんでした。
ワイヤーを更新しましたので、お手数ですが再度ご確認をお願いいたします。


 河野さまメールより
---
>ご提案いただいたように、今回は、
・現在ウェブページの下部にある求人ボタンから、サイト内の求人簡単説明ページに移動。
・そのページ内にボタンを作成していただき、クリックすると求人アドレスの記載されたメールが立ち上がる。
このような、イメージにしようとおもいます。
（求人用の情報を入力するフォームも検討しましたが、毎月多少の費用がかかるとのお話もあったのでなしとします）

**Comment by saito** [comment]
@obayashi32 

なるほどねー。
河野さんの言うように、ボタンにしてもいいかなと思いました。
ただ、ボタン押すといきなりメーラー立ち上がると驚くと思うので、

`下記の「採用申し込み」を押していただき、メールにて「履歴書」「職務経歴書」をお送りください。`

みたいな説明を入れておいて、前のバージョンのボタンにしてもらった方がいいかも。ごめん先祖返りして。

**Comment by obayashi32** [comment]
@saito 

ご確認いただきありがとうございます。
figma を調整しましたので、再度ご確認をお願いいたします。

### figma Desktop, Mobile
- `RECRUIT_button`

テキストについて、下記のどちらかがよいかなと思いますがいかがでしょうか。
お手数ですが、合わせてご確認をお願いいたします。

- 下記の「採用お申し込み」ボタンを押していただき、メールにて「履歴書」「職務経歴書」をお送りください。
- 下記の「採用お申し込み」ボタンを押していただき、「履歴書」「職務経歴書」を添付の上メールをお送りください。

**Comment by saito** [comment]
> * 下記の「採用お申し込み」ボタンを押していただき、「履歴書」「職務経歴書」を添付の上メールをお送りください。

が良いかと！

あと、ボタンにするなら

```
Mail
recruitment@maisonkei.jp
```

の部分は無くていいかなと。

**Comment by obayashi32** [comment]
@saito 

ご確認いただきありがとうございます。
テキスト修正とメールアドレスを削除し、蔭山さんにレイアウト作成依頼いたしました。

**Comment by obayashi32** [comment]
@saito 

蔭山さんにレイアウト作成いただきました。
figma よりご確認をお願いいたします。

## figma 
- Design `RECRUIT` `RECRUIT_sp`

蔭山さまメールより
---
お世話になっております。
こちら返信できておらず申し訳ございません！
求人ページのデザインをFigmaに追加したのでご確認お願いします。

テキストだけだと少し寂しかったので、
他で入口のロゴの写真をトップに使用しています。

ご確認のほどよろしくお願いいたします。

**Comment by saito** [comment]
確認しました。よいと思うので @fuji の方で実装お願いします！

一点、リストのマーカーが `■` になっているところは `li` の `list-style-type` で実装お願いします (改行したときとかその方が読みやすいので)。

**Comment by fuji** [comment]
@obayashi32 採用情報ページを作成しました。
- https://feature-issue-54-recruit-add.maisonkei.jp/
  - リンクテキストを `採用情報へ` としております、変更あれば指示お願いいたします。
- https://feature-issue-54-recruit-add.maisonkei.jp/recruit/

**Comment by obayashi32** [comment]
@fuji 
ご対応いただきありがとうございます。

### 採用情報詳細ページ
- `仕事内容` `求める人物像` などの小見出しフォントサイズがfigma レイアウトより小さく見えるのですが
環境によって異なりますでしょうか。

https://feature-issue-54-recruit-add.maisonkei.jp/recruit/
<img width="350" alt="スクリーンショット 2021-04-02 10 11 20" src="https://user-images.githubusercontent.com/31329284/113369256-e10ef580-939b-11eb-91a2-f193b4255024.png">

figma
<img width="637" alt="スクリーンショット 2021-04-02 10 12 19" src="https://user-images.githubusercontent.com/31329284/113369281-f4ba5c00-939b-11eb-98c8-ca7ed715946f.png">

- figma にてリストマーカーが`■ ` で表現されている箇所、`・` ではなく`list-style-type`  の`square` で実装いただくことは可能でしょうか。

- アルバイトの勤務時間`10:00~15:00` `17:00~21:00` の間に`、` を入れていただけますでしょうか。
<img width="932" alt="スクリーンショット 2021-04-02 10 31 21" src="https://user-images.githubusercontent.com/31329284/113370424-c722e200-939e-11eb-87ab-b5a6bd5c813a.png">

**Comment by fuji** [comment]
@obayashi32 https://github.com/toraya-group/maisonkei.jp/issues/54#issuecomment-812268879 のフィードバックに対応しました、レビューお願いいたします。
- https://feature-issue-54-recruit-add.maisonkei.jp/recruit/

**Comment by obayashi32** [comment]
@fuji 
早速ご対応いただきありがとうございます！

@saito 
他、気になる箇所等ございますでしょうか。
ご確認をお願いいたします。

https://feature-issue-54-recruit-add.maisonkei.jp/
https://feature-issue-54-recruit-add.maisonkei.jp/recruit/

**Comment by saito** [comment]
よいと思います！　蔭山さんチェックお願いします！

**Comment by obayashi32** [comment]
@saito 

ご確認いただきありがとうございます。
蔭山さん、河野さんにチェック回しました。

**Comment by obayashi32** [comment]
河野さまメールより
---
トップページのボタン、求人ページともにデザインについては違和感ありませんでした。
求人ページに記載の文言について、5ヵ所修正をお願いできればとおもいます。


- １．勤務地のあとに、店名と住所の記載をお願いいたします。

Maison KEI
412-0024　静岡県御殿場市東山527-1

- ２．勤務時間帯の表示前に小見出しの記載をお願いいたします。

勤務時間

- ３．勤務時間の下の文章の削除をお願いいたします。

下記の時間帯のなかで8時間

- ４．社員の勤務時間のあとに、労働条件の記載をお願いいたします。

＊変形労働時間制

- ５．アルバイトの勤務時間のあとの＊の文章を削除をお願いいたします。

＊2021年4月より変形労働時間制導入見込み

[20210405_修正希望箇所.pdf](https://github.com/toraya-group/maisonkei.jp/files/6256878/20210405_.pdf)

**Comment by obayashi32** [comment]
@fuji 

上記箇所の修正ご対応をお願いいたします。
念のため、figma にも反映しております。

**Comment by fuji** [comment]
@obayashi32 https://github.com/toraya-group/maisonkei.jp/issues/54#issuecomment-813243326 のフィードバック対応が完了しました、レビューお願いいたします。
- https://feature-issue-54-recruit-add.maisonkei.jp/recruit/

**Comment by obayashi32** [comment]
@fuji 

早速ご対応いただきありがとうございます。
こちらでチェック回します。

**Comment by obayashi32** [comment]
@fuji 

先方からOKいただきました。
藤原さんの良きタイミングで本番反映をお願いいたします。

Cc @saito

**Comment by fuji** [comment]
@obayashi32 live へリリースいたしました。
- https://www.maisonkei.jp/
- https://www.maisonkei.jp/recruit/

**Comment by obayashi32** [comment]
@fuji 

ありがとうございます！
こちらで先方にも報告いたしました。
