### ISSUE TITLE
ニュース記事更新

### ISSUE THREAD

**Issue by obayashi32** [toraya-group/maisonkei.jp#59]
### To Do
- 2/21 記事削除
https://www.maisonkei.jp/news/202102/21/
- 新しい記事追加

河野さまメールより
---
大林さま
お世話になっております。

Maison KEIのウェブサイト内にある「お知らせ」ページの記事の書き換えをお願いしたく、メールしました。

現在、最新のお知らせとして表示されている2/21の記事の情報が古くなってしました。

2/21の記事を削除いただきまして、最新の状況である下記の内容の記事の掲載をお願いしたくおもいます。

---

タイトル

5月末まで満席のお知らせ

本文

5月末までのご予約を承っている期間ではございますが、ランチ・ディナー共にご予約で満席となりました。

現在は、5月末までのキャンセル待ちをお伺いしております。

ご迷惑をお掛けいたしますことをお詫び申し上げますとともに、これからも何卒よろしくお願いいたします。

ご予約は、毎月1日に2か月後の末日までの分を承っております。

6月分のご予約は、4月1日（木）よりお電話にて承ります。

ご予約・お問合せ

0550-81-2231

（ご予約受付時間　営業日の10:00～11:30、15:00～17:30）

---

お忙しいところ、お手数をおかけいたしますが、お手続きをよろしくお願いいたします。

**Comment by fuji** [comment]
@obayashi32 お知らせを更新しました。
ご確認お願いいたします。
- https://feature-issue-59-news-update.daygluvw87w3l.amplifyapp.com/
- https://feature-issue-59-news-update.daygluvw87w3l.amplifyapp.com/news/202103/11/
- https://github.com/toraya-group/maisonkei.jp/pull/60

**Comment by obayashi32** [comment]
@fuji 

ありがとうございます。
こちらで先方にチェック回しました。

**Comment by obayashi32** [comment]
@fuji @saito 

本番へ反映し、先方への報告まで完了しました。

https://www.maisonkei.jp/
https://www.maisonkei.jp/news/
https://www.maisonkei.jp/news/202103/11/

クローズします。
