### ISSUE TITLE
本番サイトのワイヤーフレーム作成

### ISSUE THREAD

**Issue by saito** [toraya-group/maisonkei.jp#6]
### コンテンツ

1. 概要 (ティザーにある)
1. 出会いとプロフィール (ティザーにある)
1. 料理・メニュー
    - コンセプト
    - ランチ (コース数・価格帯)
    - ディナー (コース数・価格帯)
1. お知らせ (現地の従業員が随時更新できるページ)
    - ホームに 3 件見出し・日付
    - お知らせインデックス (20件ずつ・年アーカイブ)
    - パーマリンクで見出し・日付・写真が 1-3 点・本文
1. 交通と営業時間 (ティザーにある)
1. 予約電話番号 (ティザーにある)
    - 予約は2か月先まで
1. Instagram
    - 最新 3 件埋め込み
    - Instagram アカウントにリンク

### 検討ポイント
- 予約コンバージョンリンクを常時表示
- イメージカットの位置
- イラストを使い続けるか
- お知らせの位置 (上の方がいいかも？)
- ホームにどこまでまとめるか

**Comment by obayashi32** [comment]
@saito 

お待たせしております。
ワイヤーを作成しました。

HOME は複数パターン作成しました。
A〜D のいずれかで進行できればと思います。

また、イラストあり・なし版ワイヤーも作成しましたが
料理イラストはアクセントとして入っていても良いのではと思いました。
レストラン外観イラストは、外観写真が入るので不要な気がします。

お手数ですが、figma よりご確認をお願いいたします。

## figma
### HOME 
- `HOME A`: メイン動画上にロゴが表示されます。私的にAが一番見やすいかなと思います。
- `HOME B`: メイン画像スライド版です。ロゴは画像外に掲載されます。
- `HOME C`: イラストなしバージョンです。
- `HOME D`: HOME の下のほうにお知らせを表示しています

### お知らせ
- `NEWS TOP`: お知らせTOP です。アーカイブはページ下部にまとめました。
- `NEWS archive`: 月別アーカイブページです。
- `NEWS 詳細`: ニュース記事ページです。

**Comment by saito** [comment]
@obayashi32 
サンキュー！　以下コメントです。

- A パターンで行きましょう
- テキストはティザーと同じく左揃えに
- Instagram は、Instagram と分かるように (アイコンかロゴか文字で Instagram とするか)
- NEWS TOP / NEWS archive の画像は右側に置いた方がガタガタしなくていいかも
- NEWS archive は h1 で「お知らせ」と分かるようにするべき (お知らせトップへの導線も必要)

上記修正とセットで desktop 版も作成お願いします！

**Comment by obayashi32** [comment]
@saito 

ご確認いただきありがとうございます。
お戻しいただいた修正とPC 版ワイヤーを対応いたします。

**Comment by obayashi32** [comment]
@saito 

下記、SP版の修正対応いたしました。

> - [ ] テキストはティザーと同じく左揃えに
> - [ ] Instagram は、Instagram と分かるように (アイコンかロゴか文字で Instagram とするか)

Instagram レイアウトを2パターン作成しました。
お手数ですが、ご確認いただけますでしょうか。
- figma
  - `HOME`: プロフィール画像ありです。
  - `HOME Instagram`: プロフィール画像なしです。

<img width="722" alt="スクリーンショット 2021-01-14 9 45 20" src="https://user-images.githubusercontent.com/31329284/104529541-5563b380-564d-11eb-9333-8102cacaba52.png">

> - [ ] NEWS TOP / NEWS archive の画像は右側に置いた方がガタガタしなくていいかも
> - [ ] NEWS archive は h1 で「お知らせ」と分かるようにするべき (お知らせトップへの導線も必要)

画像配置を右側に変更し、アーカイブページのH1 とパンくずを追加しました。
<img width="351" alt="スクリーンショット 2021-01-14 10 08 42" src="https://user-images.githubusercontent.com/31329284/104531054-a4f7ae80-5650-11eb-83da-f0a8ad3c9849.png">

また、PC 版ワイヤーも作成しました。
figma よりご確認をお願いいたします。

### figma / Desktop
- HOME 
  - `MENU`: メニューはSP 版同様にハンバーガーメニューにしました。
  - `HOME`: 予約ボタンは右下に常に表示します。
  - `HOME open`: SP 版同様にクリックすると電話番号が表示されます。
- お知らせ
  - `NEWS TOP`: お知らせTOP です。アーカイブはページ下部にまとめました。
  - `NEWS archive`: 月別アーカイブページです。
  - `NEWS 詳細`: ニュース記事ページです。

**Comment by obayashi32** [comment]
📝 
- 先方にワイヤー共有済み
- 1/16 先方と掲載内容についてmtg

**Comment by obayashi32** [comment]
@saito 

蔭山さんより、下記ご相談が来ております。
ご確認をお願いいたします。

蔭山さまメールより
---
> 一点、本番サイトの制作について相談なのですが、
ワイヤーを作るのに使用していたFigmaの編集権限をいただいて、
そこでデザイン作業をさせていただく事は可能でしょうか…？
イラレですとデザインの共有に手間がかかるのでその方が制作がスムーズかと思います。

**Comment by saito** [comment]
@obayashi32 

Figma の `toraya-maisonkei` プロジェクトに蔭山さん編集権限、山野さん閲覧権限付与しておきました。

編集権限足すと月額費用が掛かるので、ひとまず蔭山さんだけにしてますが、山野さんも編集するようなら権限追加するので言ってください、ってメール返事しておいてもらえると助かります。

**Comment by saito** [comment]
蔭山さんが作業開始したらこの Issue は閉じちゃって OK です。

**Comment by obayashi32** [comment]
@saito 

ありがとうございます。
承知しました。

figma ワイヤーを諸々調整し、蔭山さんにfigma 権限付与のご報告と合わせて
デザイン進行依頼をいたしました。
蔭山さんが作業開始したらクローズします。

**Comment by obayashi32** [comment]
蔭山さんにfigma にてデザイン作業進行いただいていることが確認できましたので
こちらのissueはクローズします。
