### ISSUE TITLE
お知らせ記事追加

### ISSUE THREAD

**Issue by obayashi32** [toraya-group/maisonkei.jp#61]
河野さまメールより
---
大林さま

お世話になっております。
Maison KEIのウェブサイト内にある「お知らせ」ページに、新しい記事を追加いただきたく、メールいたしました。
新しい記事として、下記の内容を掲載いただければとおもいます。

---------

### タイトル
梅雨休みのお知らせ

### 本文
誠に勝手ながら、Maison KEIでは下記の期間、梅雨休みを予定しております。
　6月28日（月）～7月7日（水）
みなさまにはご不便をおかけいたしますが、何卒よろしくお願いいたします。

---------

梅雨休みの日程は、一マス下げて表示するイメージです。

現在、6月分の予約を4/1（木）10時開始予定としております。
タイトスケジュールのお願いとなり大変申し訳ないのですが、できましたら6月分の予約開始までにこのお知らせを公開いただけると助かります。
今日から4/1（木）10時までに公開いただける場合は、公開日の表示はその公開日で大丈夫です。（3/29、30、31、4/1）
お忙しいとおもいますので、予約開始までに公開が難しい場合は、できる範囲の早めの作業をいただければとおもいます。
4/1以降に公開の場合は、公開日を4/1の日付としてください。

お手数をおかけいたしますが、よろしくお願いします。

**Comment by obayashi32** [comment]
@fuji 

お知らせページに上記内容で記事追加をお願いいたします。
可能でしたら今日または明日までに本公開いただくことは可能でしょうか。

よろしくお願いいたします。

Cc @saito

**Comment by fuji** [comment]
@obayashi32 `梅雨休みのお知らせ` を更新しました。
ご確認お願いいたします。
- https://feature-issue-61-news-update.maisonkei.jp/
- https://feature-issue-61-news-update.maisonkei.jp/news/
- https://feature-issue-61-news-update.maisonkei.jp/news/202103/30/
- https://github.com/toraya-group/maisonkei.jp/pull/62

**Comment by obayashi32** [comment]
@fuji 

早速ご対応いただきありがとうございます！
こちらで先方にチェック回します。

**Comment by obayashi32** [comment]
先方からOKいただきましたので、本番反映し報告まで完了しました。
こちらのissueはクローズします。

ありがとうございました！
