### ISSUE TITLE
6/1 説明文、お知らせ、価格 修正

### ISSUE THREAD

**Issue by obayashi32** [toraya-group/maisonkei.jp#65]
河野さまメールより
---
お世話になっております。
Maison KEIのウェブサイトで、下記の3点について変更をお願いしたく、メールいたしました。

　1.　ページ冒頭のMaison KEIの説明文章2文目の語尾変更　
オープンしてすこし経ちましたので、2文目の語尾を過去形に変更をお願いいたします。

～～食材と水の豊かな御殿場市東山に店を構えます。
↓
～～食材と水の豊かな御殿場市東山に店を構えました。

　2．4/7掲載のお知らせ削除　
最新のお知らせが、3/30掲載の「梅雨休みのお知らせ」となるよう、4/7の記事の削除をお願いいたします。

2021.04.07 「6月末まで満席のお知らせ」
↓
（削除）

　3.　料理紹介部分の価格変更　
6/1よりコース料金がすこしアップします。下記の赤文字の料金に変更をお願いいたします。

ランチ
3,850円（4皿）
7,480円（6皿）
↓
4,500円（4皿）
8,500円（6皿）

ディナー
5,280円（4皿）
8,580円（6皿）
↓
5,500円（4皿）
9,000円（6皿）

できれば上記の3つの変更を6/1（火）からの表示開始となるとありがたいのですが、
お忙しいとおもいますので、ご無理のない範囲で作業をお願いいたします。
（6/1を大幅に過ぎるようであれば、お知らせいただけると助かります）

変更部分について、わかりづらい箇所がありましたら、お尋ねください。
お手数をおかけいたしますが、何卒よろしくお願いいたします。

**Comment by obayashi32** [comment]
@fuji 

お手数ですが、4/7 のお知らせ記事削除ご対応をお願いいたします。
>　2．4/7掲載のお知らせ削除　
> 最新のお知らせが、3/30掲載の「梅雨休みのお知らせ」となるよう、4/7の記事の削除をお願いいたします。
> - https://www.maisonkei.jp/news/
> - https://www.maisonkei.jp/news/202104/07/
>
> 2021.04.07 「6月末まで満席のお知らせ」
> ↓
> （削除）

その際、私が対応したhttps://github.com/toraya-group/maisonkei.jp/commit/9dc2d8638c05839bdcb64f06490109b02c8932cd のテストページが見られないため、
お手数ですが一緒にご確認いただけますでしょうか。

よろしくお願いいたします。

**Comment by fuji** [comment]
@obayashi32 `お知らせ`更新・テキスト修正も取り込んで反映しております。
レビューお願いします。
- https://feature-issue-65-news-update.maisonkei.jp/
- https://github.com/toraya-group/maisonkei.jp/pull/70


ブランチの名前の問題です、下記確認お願いします。
```
feature/xxx のような名前のブランチにpushすると、AmplifyNetlifyと似た感じでそのブランチ専用のサブドメインにビルド・デプロイを実行します。
```
- https://github.com/toraya-group/maisonkei.jp/issues/13#issuecomment-768944391 
> その際、私が対応した9dc2d86 のテストページが見られないため、
> お手数ですが一緒にご確認いただけますでしょうか。

**Comment by obayashi32** [comment]
@fuji 

ご対応いただきありがとうございます。
>ブランチの名前の問題です、下記確認お願いします。

テストページについてもご教示いただきありがとうございます。
ブランチ名も変えて確認したつもりだったのですが、
今後はAWSのAmplfyコンソールも確認するようにします。

ちなみに、https://github.com/toraya-group/maisonkei.jp/pull/69 とhttps://github.com/toraya-group/maisonkei.jp/pull/70 をマージする際の順番や注意することなどありますでしょうか。

**Comment by fuji** [comment]
@obayashi32 #69（はクローズしてください。） の変更も取り込んでいるので、下記のみマージお願いします。
- #70

**Comment by obayashi32** [comment]
@fuji 

承知しました！
ありがとうございます！！

**Comment by obayashi32** [comment]
@saito @fuji 

本日10:00 に修正内容を本番へ反映しました。
tps://www.maisonkei.jp/
https://www.maisonkei.jp/news/
> ・ページ冒頭のMaison KEIの説明文章2文目の語尾変更
> ・4/7掲載のお知らせ削除　
> ・料理紹介部分の価格変更　

先方にも報告済みです。
要件を満たしたので、こちらのissueはクローズします。
ありがとうございました。
