### ISSUE TITLE
3/11 記事削除、4/7 記事作成

### ISSUE THREAD

**Issue by obayashi32** [toraya-group/maisonkei.jp#66]
- 3/11 記事削除
https://www.maisonkei.jp/news/202103/11/
- 4/7 記事新規作成

## 原稿
- 日程
2021.04.07
- タイトル
6月末まで満席のお知らせ
- 本文
6月末までのご予約を承っている期間ではございますが、ランチ・ディナー共にご予約で満席となりました。
現在は、6月末までのキャンセル待ちをお伺いしております。
ご迷惑をお掛けいたしますことをお詫び申し上げますとともに、これからも何卒よろしくお願いいたします。
ご予約は、毎月1日に2か月後の末日までの分を承っております。
7月分のご予約は、5月1日（土）よりお電話にて承ります。

ご予約・お問合せ
0550-81-2231
（ご予約受付時間　営業日の10:00～11:30、15:00～17:30）

河野さまメールより
---
Maison KEIのウェブサイト内の「お知らせ」の書き換えをお願いしたく、ご連絡しました。
現在お知らせページに掲載の3/11の記事を、下記の内容に書き換えて4/7の日付で公開をお願いできればとおもいます。
（3/11の記事は消えて大丈夫です。本日の公開でなくても4/7の日付で大丈夫です）

**Comment by obayashi32** [comment]
@fuji 

上記より詳細をご確認いただき、
お知らせ記事削除と新規作成対応をお願いいたします。

**Comment by fuji** [comment]
@obayashi32 `3/11 記事削除、4/7 記事作成` が完了しました。
ご確認ください。
- https://feature-issue-66-news-update.daygluvw87w3l.amplifyapp.com/
- https://feature-issue-66-news-update.daygluvw87w3l.amplifyapp.com/news/
- https://feature-issue-66-news-update.daygluvw87w3l.amplifyapp.com/news/202104/07/
  - https://github.com/toraya-group/maisonkei.jp/pull/68

**Comment by obayashi32** [comment]
@fuji 

早速ご対応いただきありがとうございました！
本番へ反映し、先方への報告まで完了しました。

https://www.maisonkei.jp/
https://www.maisonkei.jp/news/
https://www.maisonkei.jp/news/202104/07/

Cc @saito
