### ISSUE TITLE
6/14 ニュース記事新規作成、定休日テキスト修正

### ISSUE THREAD

**Issue by obayashi32** [toraya-group/maisonkei.jp#71]
河野さまメールより
---
### 新しいお知らせの掲載
下記の内容で、お知らせの掲載をお願いできますでしょうか。

＜タイトル＞
9月のご予約開始について

＜内容＞
誠に勝手ながら、Maison　KEIでは6月28日（月）～7月7日（水）の期間、梅雨休みを予定しております。
9月のご予約につきましては、7月8日（木）より受付開始いたします。
みなさまにはご不便をおかけいたしますが、何卒よろしくお願いいたします。

＜公開日＞
6/14（月）10:00

### 定休日にある＊情報の削除
ページの定休日の表示の下に記載されている文言「＊2月1日（月）は臨時休業」を削除をお願いいたします。
こちらについてはお手すきのタイミングで大丈夫です。

**Comment by obayashi32** [comment]
@fuji 

お手数ですが、上記2つの内容をご対応いただけますでしょうか。
ニュース・定休日ともに6/14（月）の本番公開予定で、マージは私が対応いたします。

よろしくお願いいたします。

Cc @saito

**Comment by fuji** [comment]
@obayashi32 本件、対応が完了しました。
レビューお願いします。
- https://feature-issue-71-news-update.daygluvw87w3l.amplifyapp.com/
- https://feature-issue-71-news-update.daygluvw87w3l.amplifyapp.com/news/
- https://feature-issue-71-news-update.daygluvw87w3l.amplifyapp.com/news/202106/14/
- https://github.com/toraya-group/maisonkei.jp/pull/72

**Comment by obayashi32** [comment]
@fuji 

ご対応いただきありがとうございます！
確認できましたので、先方にもチェック回します。

**Comment by obayashi32** [comment]
@fuji 

すみません、お知らせ内の「Maison KEI」表記で
「Maison」と「KEI」の間を全角スペースではなく半角スペースに修正いただけますでしょうか。

- 現状: Maison　KEI
- 修正後: Maison KEI

お手数おかけいたします。
よろしくお願いいたします。

**Comment by fuji** [comment]
@obayashi32 https://github.com/toraya-group/maisonkei.jp/issues/71#issuecomment-857418146 の件、対応が完了しました。
- https://feature-issue-71-news-update.daygluvw87w3l.amplifyapp.com/news/202106/14/

**Comment by obayashi32** [comment]
@fuji 

お手数おかけいたしました。
修正いただきありがとうございます！

**Comment by obayashi32** [comment]
@saito @fuji 

本日10:00 に本番へ反映し、先方にも報告完了しました。
ありがとうございました！

https://www.maisonkei.jp/
https://www.maisonkei.jp/news/
https://www.maisonkei.jp/news/202106/14/
