### ISSUE TITLE
交通案内、採用情報ページテキスト修正

### ISSUE THREAD

**Issue by obayashi32** [toraya-group/maisonkei.jp#73]
河野さまメールより
---
メールにてお尋ねいただいたプロフィールと出会いについてですが、
これまでに何回か修正いただいていて、現在はいまの情報で良いようです。
気にかけていただき、ありがとうございます。

別の項目となりますが、下記の2点について変更・追記のお願いできますでしょうか。
下記の赤文字部分です。

■交通案内の＜お車でお越しの方＞の3行目
・修正前　
→ 300メートル進むと、右側に「とらや工房 東山旧岸邸 駐車場」

・修正後　
→ 300メートル進むと、左側に「Maison KEI 駐車場」

■採用情報ページの　給与の箇所
・修正前
給与
正社員基本給16万5600円~
＊ご経験により応相談

・修正後
給与
正社員基本給16万5600円~
＊ご経験により応相談
【23歳モデル給】
月額255,318円  基本給+超勤代+手当（資格+住宅）
＊他に賞与あり

赤文字部分を黒字で変更・追記いただければとおもいます。
わかりづらければ、お尋ねください。
お忙しいところ恐縮ではございますが、何卒よろしくお願いいたします。

**Comment by obayashi32** [comment]
@fuji 

採用ページを修正して、staging まで反映したのですが
間違っていることに気がつきまして…
- https://feature-issue-73-access-recruit.maisonkei.jp/recruit/

大変お手数ですが、下記の方法をご教示いただけますでしょうか。

- https://github.com/toraya-group/maisonkei.jp/pull/74 の内容を修正または、元に戻す方法
- 赤枠内の箇所を正社員基本給下部に表示する方法

<img width="707" alt="スクリーンショット 2021-06-15 12 46 57" src="https://user-images.githubusercontent.com/31329284/121990130-3e7de480-cdd8-11eb-88f7-3d712e018952.png">


よろしくお願いいたします。

**Comment by fuji** [comment]
@obayashi32 インラインで回答します。
#73 へコミットすれば反映されます。
> #74 の内容を修正または、元に戻す方法

下記 `<dd></dd>` 内に追加してください。
```
<dd>基本給16万5600円~<br><span class="caption">＊ご経験により応相談</span></dd>
```
> 赤枠内の箇所を正社員基本給下部に表示する方法

**Comment by obayashi32** [comment]
@fuji 

ご教示いただきありがとうございます！
無事に修正できました。
こちらで先方へ確認回します。

- https://feature-issue-73-access-recruit.maisonkei.jp/
- https://feature-issue-73-access-recruit.maisonkei.jp/recruit/

**Comment by obayashi32** [comment]
本番へ反映し、先方への報告まで完了しました。
クローズします。

https://www.maisonkei.jp/
https://www.maisonkei.jp/recruit/
