### ISSUE TITLE
9月中 ニュース記事新規追加

### ISSUE THREAD

**Issue by obayashi32** [toraya-group/maisonkei.jp#79]
河野さまメールより
---
10月2日（木）より受付開始の12月分の予約について、新しいお知らせを掲載したいと考えています。
添付の内容で、今月中にウェブのお知らせページに掲載をお願いできますでしょうか。

https://www.maisonkei.jp/news/

## 公開日
- 9月中

## 原稿
- タイトル
12月のご予約について

- 本文

誠に勝手ながら10月1日（金）10:00より受付開始の12月のご予約は、12月2日（木）～19日（日）分のご予約とさせていただきます。

12月20日（月）以降は、内容を変えて営業いたします。
詳細と受付開始時期のお知らせにつきましては、10月下旬を予定しております。
みなさまにはご不便をおかけいたしますが、何卒よろしくお願いいたします。

**Comment by obayashi32** [comment]
@fuji 

お手数ですが、上記の内容でニュース新規追加ご対応いただけますでしょうか。
マージは私が対応いたします。

よろしくお願いいたします。

Cc @saito

**Comment by fuji** [comment]
@obayashi32 ニュース記事更新しました。
ご確認お願いいたします。
- https://feature-issue-79-news-update.daygluvw87w3l.amplifyapp.com/
- https://feature-issue-79-news-update.daygluvw87w3l.amplifyapp.com/news/
- https://feature-issue-79-news-update.daygluvw87w3l.amplifyapp.com/news/202109/24/

**Comment by obayashi32** [comment]
@fuji 

早速ご対応いただきありがとうございます！
先方へチェック回しました。

**Comment by obayashi32** [comment]
@fuji 

度々のお願いですみません。
下記内容もご対応いただき、そのまま本番へ反映いただけますでしょうか。

- 6/14に公開された「9月の予約開始について」ページの削除
 *「梅雨休みのお知らせ」の次が今回反映いただく「12月のご予約について」となるイメージです。

<img width="1015" alt="スクリーンショット 2021-09-24 15 18 02" src="https://user-images.githubusercontent.com/31329284/134627500-58aea3e2-16c5-4471-8c32-04942e2aa6f9.png">

**Comment by fuji** [comment]
@obayashi32 https://github.com/toraya-group/maisonkei.jp/issues/79#issuecomment-926376159 を対応の上、公開しました。
- https://www.maisonkei.jp/
- https://www.maisonkei.jp/news/
- https://www.maisonkei.jp/news/202109/24/

**Comment by obayashi32** [comment]
@fuji 

ご対応いただきありがとうございました。
先方への報告まで完了しました。

Cc @saito
